/**
 * OSIRIS — Moldova Comprehensive Offline Gazetteer
 * Contains exact geographic coordinates, administrative hierarchies, and multilingual aliases
 * for all 32 districts (raioane), municipalities, autonomous regions (Găgăuzia), Transnistria,
 * border crossing points, airports, and major settlements in Republic of Moldova.
 */

import type { GeocodedLocation } from '../types';

export interface GazetteerEntry {
  name: string;
  nameRo: string;
  nameRu: string;
  nameEn: string;
  aliases: string[];
  district: string;
  regionType: 'MUNICIPALITY' | 'DISTRICT' | 'CITY' | 'VILLAGE' | 'BORDER_CROSSING' | 'AIRPORT' | 'HIGHWAY_JUNCTION';
  lat: number;
  lng: number;
}

export const MOLDOVA_GAZETTEER: GazetteerEntry[] = [
  // ── Municipalities & Major Cities ──
  {
    name: 'Chișinău',
    nameRo: 'Chișinău',
    nameRu: 'Кишинёв',
    nameEn: 'Chisinau',
    aliases: ['chisinau', 'chisinau', 'кишинев', 'кишинёв', 'kischinew', 'kishinev', 'capitala'],
    district: 'Municipiul Chișinău',
    regionType: 'MUNICIPALITY',
    lat: 47.0105,
    lng: 28.8638,
  },
  {
    name: 'Bălți',
    nameRo: 'Bălți',
    nameRu: 'Бельцы',
    nameEn: 'Balti',
    aliases: ['balti', 'бельцы', 'beltsy', 'baltzi', 'municipiul balti'],
    district: 'Municipiul Bălți',
    regionType: 'MUNICIPALITY',
    lat: 47.7617,
    lng: 27.9289,
  },
  {
    name: 'Tiraspol',
    nameRo: 'Tiraspol',
    nameRu: 'Тирасполь',
    nameEn: 'Tiraspol',
    aliases: ['tiraspol', 'тирасполь'],
    district: 'Unitatea Teritorială din Stânga Nistrului',
    regionType: 'MUNICIPALITY',
    lat: 46.8403,
    lng: 29.6433,
  },
  {
    name: 'Bender (Tighina)',
    nameRo: 'Bender',
    nameRu: 'Бендеры',
    nameEn: 'Bender',
    aliases: ['bender', 'tighina', 'бендеры', 'тигина'],
    district: 'Municipiul Bender',
    regionType: 'MUNICIPALITY',
    lat: 46.8317,
    lng: 29.4778,
  },
  {
    name: 'Comrat',
    nameRo: 'Comrat',
    nameRu: 'Комрат',
    nameEn: 'Comrat',
    aliases: ['comrat', 'комрат', 'gagauzia', 'utag'],
    district: 'UTA Găgăuzia',
    regionType: 'MUNICIPALITY',
    lat: 46.3006,
    lng: 28.6572,
  },
  {
    name: 'Cahul',
    nameRo: 'Cahul',
    nameRu: 'Кагул',
    nameEn: 'Cahul',
    aliases: ['cahul', 'кагул', 'municipiul cahul'],
    district: 'Raionul Cahul',
    regionType: 'MUNICIPALITY',
    lat: 45.9075,
    lng: 28.1944,
  },
  {
    name: 'Ungheni',
    nameRo: 'Ungheni',
    nameRu: 'Унгены',
    nameEn: 'Ungheni',
    aliases: ['ungheni', 'унгены', 'municipiul ungheni'],
    district: 'Raionul Ungheni',
    regionType: 'MUNICIPALITY',
    lat: 47.2042,
    lng: 27.7958,
  },
  {
    name: 'Soroca',
    nameRo: 'Soroca',
    nameRu: 'Сороки',
    nameEn: 'Soroca',
    aliases: ['soroca', 'сороки', 'cetatea soroca', 'municipiul soroca'],
    district: 'Raionul Soroca',
    regionType: 'MUNICIPALITY',
    lat: 48.1566,
    lng: 28.2849,
  },
  {
    name: 'Orhei',
    nameRo: 'Orhei',
    nameRu: 'Оргеев',
    nameEn: 'Orhei',
    aliases: ['orhei', 'оргеев', 'orheiul vechi', 'municipiul orhei'],
    district: 'Raionul Orhei',
    regionType: 'MUNICIPALITY',
    lat: 47.3831,
    lng: 28.8231,
  },
  {
    name: 'Strășeni',
    nameRo: 'Strășeni',
    nameRu: 'Страшены',
    nameEn: 'Straseni',
    aliases: ['straseni', 'страшены', 'municipiul straseni'],
    district: 'Raionul Strășeni',
    regionType: 'MUNICIPALITY',
    lat: 47.1414,
    lng: 28.6103,
  },
  {
    name: 'Hîncești',
    nameRo: 'Hîncești',
    nameRu: 'Хынчешты',
    nameEn: 'Hincesti',
    aliases: ['hincesti', 'hancesti', 'хынчешты', 'municipiul hincesti'],
    district: 'Raionul Hîncești',
    regionType: 'MUNICIPALITY',
    lat: 46.8258,
    lng: 28.5908,
  },
  {
    name: 'Edineț',
    nameRo: 'Edineț',
    nameRu: 'Единцы',
    nameEn: 'Edinet',
    aliases: ['edinet', 'единцы', 'municipiul edinet'],
    district: 'Raionul Edineț',
    regionType: 'MUNICIPALITY',
    lat: 48.1681,
    lng: 27.3050,
  },
  {
    name: 'Căușeni',
    nameRo: 'Căușeni',
    nameRu: 'Каушаны',
    nameEn: 'Causeni',
    aliases: ['causeni', 'каушаны', 'municipiul causeni'],
    district: 'Raionul Căușeni',
    regionType: 'MUNICIPALITY',
    lat: 46.6433,
    lng: 29.4142,
  },
  {
    name: 'Drochia',
    nameRo: 'Drochia',
    nameRu: 'Дрокия',
    nameEn: 'Drochia',
    aliases: ['drochia', 'дрокия'],
    district: 'Raionul Drochia',
    regionType: 'CITY',
    lat: 48.0350,
    lng: 27.8161,
  },
  {
    name: 'Fălești',
    nameRo: 'Fălești',
    nameRu: 'Фалешты',
    nameEn: 'Falesti',
    aliases: ['falesti', 'фалешты'],
    district: 'Raionul Fălești',
    regionType: 'CITY',
    lat: 47.5744,
    lng: 27.7092,
  },
  {
    name: 'Florești',
    nameRo: 'Florești',
    nameRu: 'Флорешты',
    nameEn: 'Floresti',
    aliases: ['floresti', 'флорешты'],
    district: 'Raionul Florești',
    regionType: 'CITY',
    lat: 47.8933,
    lng: 28.3014,
  },
  {
    name: 'Ialoveni',
    nameRo: 'Ialoveni',
    nameRu: 'Яловены',
    nameEn: 'Ialoveni',
    aliases: ['ialoveni', 'яловены', 'mileștii mici', 'milestii mici'],
    district: 'Raionul Ialoveni',
    regionType: 'CITY',
    lat: 46.9431,
    lng: 28.7778,
  },
  {
    name: 'Cimișlia',
    nameRo: 'Cimișlia',
    nameRu: 'Чимишлия',
    nameEn: 'Cimislia',
    aliases: ['cimislia', 'чимишлия'],
    district: 'Raionul Cimișlia',
    regionType: 'CITY',
    lat: 46.5222,
    lng: 28.7842,
  },
  {
    name: 'Rîșcani',
    nameRo: 'Rîșcani',
    nameRu: 'Рышканы',
    nameEn: 'Riscani',
    aliases: ['riscani', 'рышканы', 'rascani'],
    district: 'Raionul Rîșcani',
    regionType: 'CITY',
    lat: 47.9572,
    lng: 27.5539,
  },
  {
    name: 'Sîngerei',
    nameRo: 'Sîngerei',
    nameRu: 'Сынжерея',
    nameEn: 'Singerei',
    aliases: ['singerei', 'сынжерея', 'sangerei'],
    district: 'Raionul Sîngerei',
    regionType: 'CITY',
    lat: 47.6361,
    lng: 28.1417,
  },
  {
    name: 'Taraclia',
    nameRo: 'Taraclia',
    nameRu: 'Тараклия',
    nameEn: 'Taraclia',
    aliases: ['taraclia', 'тараклия'],
    district: 'Raionul Taraclia',
    regionType: 'CITY',
    lat: 45.9000,
    lng: 28.6686,
  },
  {
    name: 'Rezina',
    nameRo: 'Rezina',
    nameRu: 'Резина',
    nameEn: 'Rezina',
    aliases: ['rezina', 'резина', 'saharna'],
    district: 'Raionul Rezina',
    regionType: 'CITY',
    lat: 47.7492,
    lng: 28.9622,
  },
  {
    name: 'Rîbnița',
    nameRo: 'Rîbnița',
    nameRu: 'Рыбница',
    nameEn: 'Ribnita',
    aliases: ['ribnita', 'рыбница', 'rybnitsa'],
    district: 'Unitatea Teritorială din Stânga Nistrului',
    regionType: 'CITY',
    lat: 47.7667,
    lng: 29.0000,
  },
  {
    name: 'Dubăsari',
    nameRo: 'Dubăsari',
    nameRu: 'Дубоссары',
    nameEn: 'Dubasari',
    aliases: ['dubasari', 'дубоссары', 'cocieri'],
    district: 'Raionul Dubăsari',
    regionType: 'CITY',
    lat: 47.2667,
    lng: 29.1667,
  },
  {
    name: 'Anenii Noi',
    nameRo: 'Anenii Noi',
    nameRu: 'Новые Анены',
    nameEn: 'Anenii Noi',
    aliases: ['anenii noi', 'новые анены', 'aneni'],
    district: 'Raionul Anenii Noi',
    regionType: 'CITY',
    lat: 46.8822,
    lng: 29.2294,
  },
  {
    name: 'Călărași',
    nameRo: 'Călărași',
    nameRu: 'Калараш',
    nameEn: 'Calarasi',
    aliases: ['calarasi', 'калараш'],
    district: 'Raionul Călărași',
    regionType: 'CITY',
    lat: 47.2544,
    lng: 28.3078,
  },
  {
    name: 'Nisporeni',
    nameRo: 'Nisporeni',
    nameRu: 'Ниспорены',
    nameEn: 'Nisporeni',
    aliases: ['nisporeni', 'ниспорены'],
    district: 'Raionul Nisporeni',
    regionType: 'CITY',
    lat: 47.0817,
    lng: 28.1783,
  },
  {
    name: 'Cantemir',
    nameRo: 'Cantemir',
    nameRu: 'Кантемир',
    nameEn: 'Cantemir',
    aliases: ['cantemir', 'кантемир'],
    district: 'Raionul Cantemir',
    regionType: 'CITY',
    lat: 46.2778,
    lng: 28.2008,
  },
  {
    name: 'Leova',
    nameRo: 'Leova',
    nameRu: 'Леова',
    nameEn: 'Leova',
    aliases: ['leova', 'леова'],
    district: 'Raionul Leova',
    regionType: 'CITY',
    lat: 46.4786,
    lng: 28.2553,
  },
  {
    name: 'Briceni',
    nameRo: 'Briceni',
    nameRu: 'Бричаны',
    nameEn: 'Briceni',
    aliases: ['briceni', 'бричаны'],
    district: 'Raionul Briceni',
    regionType: 'CITY',
    lat: 48.3611,
    lng: 27.0833,
  },
  {
    name: 'Ocnița',
    nameRo: 'Ocnița',
    nameRu: 'Окница',
    nameEn: 'Ocnita',
    aliases: ['ocnita', 'окница', 'otaci'],
    district: 'Raionul Ocnița',
    regionType: 'CITY',
    lat: 48.4442,
    lng: 27.4381,
  },
  {
    name: 'Dondușeni',
    nameRo: 'Dondușeni',
    nameRu: 'Дондюшаны',
    nameEn: 'Donduseni',
    aliases: ['donduseni', 'дондюшаны', 'taul'],
    district: 'Raionul Dondușeni',
    regionType: 'CITY',
    lat: 48.2428,
    lng: 27.5850,
  },
  {
    name: 'Glodeni',
    nameRo: 'Glodeni',
    nameRu: 'Глодяны',
    nameEn: 'Glodeni',
    aliases: ['glodeni', 'глодяны', 'padurea domneasca'],
    district: 'Raionul Glodeni',
    regionType: 'CITY',
    lat: 47.7708,
    lng: 27.5144,
  },
  {
    name: 'Șoldănești',
    nameRo: 'Șoldănești',
    nameRu: 'Шолданешты',
    nameEn: 'Soldanesti',
    aliases: ['soldanesti', 'шолданешты'],
    district: 'Raionul Șoldănești',
    regionType: 'CITY',
    lat: 47.8161,
    lng: 28.7967,
  },
  {
    name: 'Telenești',
    nameRo: 'Telenești',
    nameRu: 'Теленешты',
    nameEn: 'Telenesti',
    aliases: ['telenesti', 'теленешты'],
    district: 'Raionul Telenești',
    regionType: 'CITY',
    lat: 47.4997,
    lng: 28.3656,
  },
  {
    name: 'Criuleni',
    nameRo: 'Criuleni',
    nameRu: 'Криуляны',
    nameEn: 'Criuleni',
    aliases: ['criuleni', 'криуляны', 'vadul lui voda'],
    district: 'Raionul Criuleni',
    regionType: 'CITY',
    lat: 47.2094,
    lng: 29.1581,
  },
  {
    name: 'Ștefan Vodă',
    nameRo: 'Ștefan Vodă',
    nameRu: 'Штефан-Водэ',
    nameEn: 'Stefan Voda',
    aliases: ['stefan voda', 'штефан водэ', 'штефан-водэ', 'purcari', 'palanca'],
    district: 'Raionul Ștefan Vodă',
    regionType: 'CITY',
    lat: 46.5139,
    lng: 29.6631,
  },
  {
    name: 'Basarabeasca',
    nameRo: 'Basarabeasca',
    nameRu: 'Бессарабка',
    nameEn: 'Basarabeasca',
    aliases: ['basarabeasca', 'бессарабка', 'басарабяска'],
    district: 'Raionul Basarabeasca',
    regionType: 'CITY',
    lat: 46.3333,
    lng: 28.9667,
  },
  {
    name: 'Ceadîr-Lunga',
    nameRo: 'Ceadîr-Lunga',
    nameRu: 'Чадыр-Лунга',
    nameEn: 'Ceadir-Lunga',
    aliases: ['ceadir-lunga', 'ceadir lunga', 'чадыр-лунга', 'чадыр лунга'],
    district: 'UTA Găgăuzia',
    regionType: 'CITY',
    lat: 46.0542,
    lng: 28.8317,
  },
  {
    name: 'Vulcănești',
    nameRo: 'Vulcănești',
    nameRu: 'Вулканешты',
    nameEn: 'Vulcanesti',
    aliases: ['vulcanesti', 'вулканешты'],
    district: 'UTA Găgăuzia',
    regionType: 'CITY',
    lat: 45.6833,
    lng: 28.4028,
  },
  {
    name: 'Giurgiulești',
    nameRo: 'Giurgiulești',
    nameRu: 'Джурджулешты',
    nameEn: 'Giurgiulesti',
    aliases: ['giurgiulesti', 'джурджулешты', 'port giurgiulesti', 'portul giurgiulesti'],
    district: 'Raionul Cahul',
    regionType: 'VILLAGE',
    lat: 45.4819,
    lng: 28.1972,
  },

  // ── Strategic Border Crossings ──
  {
    name: 'Leușeni-Albița',
    nameRo: 'PTF Leușeni',
    nameRu: 'КПП Леушены',
    nameEn: 'Leuseni Border Crossing',
    aliases: ['leuseni', 'albita', 'ptf leuseni', 'vama leuseni', 'леушены'],
    district: 'Raionul Hîncești',
    regionType: 'BORDER_CROSSING',
    lat: 46.8292,
    lng: 28.1633,
  },
  {
    name: 'Sculeni',
    nameRo: 'PTF Sculeni',
    nameRu: 'КПП Скуляны',
    nameEn: 'Sculeni Border Crossing',
    aliases: ['sculeni', 'ptf sculeni', 'vama sculeni', 'скуляны'],
    district: 'Raionul Ungheni',
    regionType: 'BORDER_CROSSING',
    lat: 47.3325,
    lng: 27.6067,
  },
  {
    name: 'Costești-Stânca',
    nameRo: 'PTF Costești',
    nameRu: 'КПП Костешты',
    nameEn: 'Costesti Border Crossing',
    aliases: ['costesti', 'stanca', 'ptf costesti', 'vama costesti', 'костешты'],
    district: 'Raionul Rîșcani',
    regionType: 'BORDER_CROSSING',
    lat: 47.8383,
    lng: 27.2344,
  },
  {
    name: 'Giurgiulești-Galați',
    nameRo: 'PTF Giurgiulești',
    nameRu: 'КПП Джурджулешты',
    nameEn: 'Giurgiulesti Border Crossing',
    aliases: ['vama giurgiulesti', 'ptf giurgiulesti'],
    district: 'Raionul Cahul',
    regionType: 'BORDER_CROSSING',
    lat: 45.4744,
    lng: 28.2047,
  },
  {
    name: 'Cahul-Oancea',
    nameRo: 'PTF Cahul-Oancea',
    nameRu: 'КПП Кагул-Оанча',
    nameEn: 'Cahul-Oancea Border Crossing',
    aliases: ['oancea', 'ptf cahul', 'vama cahul'],
    district: 'Raionul Cahul',
    regionType: 'BORDER_CROSSING',
    lat: 45.9181,
    lng: 28.1650,
  },
  {
    name: 'Otaci-Moghilău',
    nameRo: 'PTF Otaci',
    nameRu: 'КПП Отачь-Могилёв-Подольский',
    nameEn: 'Otaci Border Crossing',
    aliases: ['otaci', 'moghilau', 'ptf otaci', 'отачь', 'могилев-подольский'],
    district: 'Raionul Ocnița',
    regionType: 'BORDER_CROSSING',
    lat: 48.4389,
    lng: 27.7944,
  },
  {
    name: 'Palanca-Maiaki-Udobnoe',
    nameRo: 'PTF Palanca',
    nameRu: 'КПП Паланка',
    nameEn: 'Palanca Border Crossing',
    aliases: ['palanca', 'maiaki', 'ptf palanca', 'паланка', 'маяки'],
    district: 'Raionul Ștefan Vodă',
    regionType: 'BORDER_CROSSING',
    lat: 46.4167,
    lng: 30.1000,
  },
  {
    name: 'Tudora-Starokazacie',
    nameRo: 'PTF Tudora',
    nameRu: 'КПП Тудора',
    nameEn: 'Tudora Border Crossing',
    aliases: ['tudora', 'starokazacie', 'ptf tudora', 'тудора'],
    district: 'Raionul Ștefan Vodă',
    regionType: 'BORDER_CROSSING',
    lat: 46.4381,
    lng: 30.0619,
  },
  {
    name: 'Criva-Mamalîga',
    nameRo: 'PTF Criva',
    nameRu: 'КПП Крива',
    nameEn: 'Criva Border Crossing',
    aliases: ['criva', 'mamaliga', 'ptf criva', 'крива'],
    district: 'Raionul Briceni',
    regionType: 'BORDER_CROSSING',
    lat: 48.2742,
    lng: 26.7869,
  },

  // ── Aviation & Airports ──
  {
    name: 'Aeroportul Internațional Chișinău (KIV / LUKK)',
    nameRo: 'Aeroportul Internațional Chișinău',
    nameRu: 'Международный Аэропорт Кишинёв',
    nameEn: 'Chisinau International Airport',
    aliases: ['kiv', 'lukk', 'aeroport chisinau', 'aeroportul chisinau', 'аэропорт кишинев'],
    district: 'Municipiul Chișinău',
    regionType: 'AIRPORT',
    lat: 47.0272,
    lng: 28.9314,
  },
  {
    name: 'Aeroportul Internațional Bălți-Leadoveni (BZY / LUBL)',
    nameRo: 'Aeroportul Internațional Bălți-Leadoveni',
    nameRu: 'Международный Аэропорт Бельцы-Лядовены',
    nameEn: 'Balti-Leadoveni International Airport',
    aliases: ['bzy', 'lubl', 'aeroport balti', 'leadoveni', 'аэропорт бельцы'],
    district: 'Municipiul Bălți',
    regionType: 'AIRPORT',
    lat: 47.8383,
    lng: 27.7811,
  },
  {
    name: 'Aeroportul Internațional Mărculești (MLD / LUKM)',
    nameRo: 'Aeroportul Internațional Liber Mărculești',
    nameRu: 'Международный Аэропорт Маркулешты',
    nameEn: 'Marculesti International Airport',
    aliases: ['mld', 'lukm', 'marculesti', 'aeroport marculesti', 'маркулешты'],
    district: 'Raionul Florești',
    regionType: 'AIRPORT',
    lat: 47.8636,
    lng: 28.2133,
  },
  {
    name: 'Aerodromul Tiraspol (LUTR)',
    nameRo: 'Aerodromul Tiraspol',
    nameRu: 'Аэродром Тирасполь',
    nameEn: 'Tiraspol Airfield',
    aliases: ['lutr', 'aeroport tiraspol', 'aerodrom tiraspol', 'аэродром тирасполь'],
    district: 'Unitatea Teritorială din Stânga Nistrului',
    regionType: 'AIRPORT',
    lat: 46.8700,
    lng: 29.5900,
  },
];

/**
 * Normalizes text for gazetteer lookup (lowercase, stripped punctuation, diacritic normalization).
 */
export function normalizeText(text: string): string {
  return text
    .toLowerCase()
    .replace(/[ăâ]/g, 'a')
    .replace(/[îï]/g, 'i')
    .replace(/[șş]/g, 's')
    .replace(/[țţ]/g, 't')
    .replace(/[ё]/g, 'е')
    .replace(/[^\w\s\u0400-\u04FF]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Extracts geocoded location from a freeform title or article text.
 */
export function extractMoldovaLocation(text: string): GeocodedLocation | undefined {
  if (!text || text.trim().length === 0) return undefined;
  const normalized = normalizeText(text);

  let bestEntry: GazetteerEntry | null = null;
  let bestConfidence = 0;

  const paddedText = ` ${normalized} `;

  for (const entry of MOLDOVA_GAZETTEER) {
    // Check aliases
    for (const alias of entry.aliases) {
      const normalizedAlias = normalizeText(alias);
      if (paddedText.includes(` ${normalizedAlias} `)) {
        const confidence = normalizedAlias.length > 5 ? 0.95 : 0.85;
        if (confidence > bestConfidence) {
          bestConfidence = confidence;
          bestEntry = entry;
        }
      }
    }
  }

  if (bestEntry) {
    return {
      name: bestEntry.name,
      nameRo: bestEntry.nameRo,
      nameRu: bestEntry.nameRu,
      nameEn: bestEntry.nameEn,
      district: bestEntry.district,
      regionType: bestEntry.regionType,
      lat: bestEntry.lat,
      lng: bestEntry.lng,
      confidence: bestConfidence,
      source: 'GAZETTEER',
    };
  }

  return undefined;
}
