/**
 * OSIRIS — Moldova Border Crossing Points & Customs Intelligence
 * Real-time monitoring of border crossing points with Romania (EU) and Ukraine.
 */

import { MOLDOVA_CONFIG } from '../config';
import { normalizeBorderCrossing } from '../normalizers/border-normalizer';
import { fetchWithMoldovaCache } from '../cache/moldova-cache';
import type { MoldovaBorderCrossing } from '../types';

const BORDER_CROSSINGS_DATA: Array<Parameters<typeof normalizeBorderCrossing>[0]> = [
  // ── Romania Border (EU Eastern Frontier) ──
  {
    id: 'ptf-leuseni',
    name: 'Leușeni',
    counterpartName: 'Albița (RO)',
    neighborCountry: 'RO',
    type: 'ROAD',
    lat: 46.8292,
    lng: 28.1633,
    status: 'NORMAL',
    waitTimeCarsMinutes: 15,
    waitTimeTrucksMinutes: 45,
    waitTimeBusesMinutes: 20,
    isOpen24h: true,
    pedestrianAllowed: false,
    liveCameraId: 'cam-leuseni-01',
  },
  {
    id: 'ptf-sculeni',
    name: 'Sculeni',
    counterpartName: 'Sculeni (RO)',
    neighborCountry: 'RO',
    type: 'ROAD',
    lat: 47.3325,
    lng: 27.6067,
    status: 'NORMAL',
    waitTimeCarsMinutes: 10,
    waitTimeTrucksMinutes: 30,
    waitTimeBusesMinutes: 15,
    isOpen24h: true,
    pedestrianAllowed: true,
    liveCameraId: 'cam-sculeni-01',
  },
  {
    id: 'ptf-giurgiulesti-ro',
    name: 'Giurgiulești-Galați',
    counterpartName: 'Galați (RO)',
    neighborCountry: 'RO',
    type: 'ROAD',
    lat: 45.4744,
    lng: 28.2047,
    status: 'NORMAL',
    waitTimeCarsMinutes: 20,
    waitTimeTrucksMinutes: 60,
    waitTimeBusesMinutes: 20,
    isOpen24h: true,
    pedestrianAllowed: true,
    liveCameraId: 'cam-giurgiulesti-01',
  },
  {
    id: 'ptf-costesti',
    name: 'Costești-Stânca',
    counterpartName: 'Stânca (RO)',
    neighborCountry: 'RO',
    type: 'ROAD',
    lat: 47.8383,
    lng: 27.2344,
    status: 'NORMAL',
    waitTimeCarsMinutes: 10,
    waitTimeTrucksMinutes: 25,
    waitTimeBusesMinutes: 10,
    isOpen24h: true,
    pedestrianAllowed: false,
  },
  {
    id: 'ptf-cahul',
    name: 'Cahul-Oancea',
    counterpartName: 'Oancea (RO)',
    neighborCountry: 'RO',
    type: 'ROAD',
    lat: 45.9181,
    lng: 28.1650,
    status: 'NORMAL',
    waitTimeCarsMinutes: 10,
    waitTimeTrucksMinutes: 20,
    waitTimeBusesMinutes: 10,
    isOpen24h: true,
    pedestrianAllowed: true,
  },
  {
    id: 'ptf-lipcani',
    name: 'Lipcani-Rădăuți Prut',
    counterpartName: 'Rădăuți Prut (RO)',
    neighborCountry: 'RO',
    type: 'ROAD',
    lat: 48.2619,
    lng: 26.8047,
    status: 'NORMAL',
    waitTimeCarsMinutes: 5,
    waitTimeTrucksMinutes: 15,
    waitTimeBusesMinutes: 5,
    isOpen24h: false,
    pedestrianAllowed: true,
  },
  {
    id: 'ptf-ungheni-rail',
    name: 'Ungheni Feroviar',
    counterpartName: 'Ungheni Prut (RO)',
    neighborCountry: 'RO',
    type: 'RAIL',
    lat: 47.2042,
    lng: 27.7958,
    status: 'NORMAL',
    waitTimeCarsMinutes: 0,
    waitTimeTrucksMinutes: 0,
    waitTimeBusesMinutes: 0,
    isOpen24h: true,
    pedestrianAllowed: false,
  },

  // ── Ukraine Border ──
  {
    id: 'ptf-otaci',
    name: 'Otaci',
    counterpartName: 'Moghilău / Mohyliv-Podilskyi (UA)',
    neighborCountry: 'UA',
    type: 'ROAD',
    lat: 48.4389,
    lng: 27.7944,
    status: 'NORMAL',
    waitTimeCarsMinutes: 20,
    waitTimeTrucksMinutes: 50,
    waitTimeBusesMinutes: 25,
    isOpen24h: true,
    pedestrianAllowed: true,
    liveCameraId: 'cam-otaci-01',
  },
  {
    id: 'ptf-palanca',
    name: 'Palanca',
    counterpartName: 'Maiaki-Udobnoe (UA)',
    neighborCountry: 'UA',
    type: 'ROAD',
    lat: 46.4167,
    lng: 30.1000,
    status: 'NORMAL',
    waitTimeCarsMinutes: 15,
    waitTimeTrucksMinutes: 40,
    waitTimeBusesMinutes: 20,
    isOpen24h: true,
    pedestrianAllowed: false,
    liveCameraId: 'cam-palanca-01',
  },
  {
    id: 'ptf-tudora',
    name: 'Tudora',
    counterpartName: 'Starokazacie (UA)',
    neighborCountry: 'UA',
    type: 'ROAD',
    lat: 46.4381,
    lng: 30.0619,
    status: 'NORMAL',
    waitTimeCarsMinutes: 10,
    waitTimeTrucksMinutes: 30,
    waitTimeBusesMinutes: 15,
    isOpen24h: true,
    pedestrianAllowed: false,
  },
  {
    id: 'ptf-criva',
    name: 'Criva',
    counterpartName: 'Mamalîga (UA)',
    neighborCountry: 'UA',
    type: 'ROAD',
    lat: 48.2742,
    lng: 26.7869,
    status: 'NORMAL',
    waitTimeCarsMinutes: 15,
    waitTimeTrucksMinutes: 35,
    waitTimeBusesMinutes: 15,
    isOpen24h: true,
    pedestrianAllowed: true,
  },
  {
    id: 'ptf-giurgiulesti-ua',
    name: 'Giurgiulești-Reni',
    counterpartName: 'Reni (UA)',
    neighborCountry: 'UA',
    type: 'ROAD',
    lat: 45.4789,
    lng: 28.2167,
    status: 'NORMAL',
    waitTimeCarsMinutes: 15,
    waitTimeTrucksMinutes: 55,
    waitTimeBusesMinutes: 20,
    isOpen24h: true,
    pedestrianAllowed: true,
  },
  {
    id: 'ptf-briceni',
    name: 'Briceni-Rossoșanî',
    counterpartName: 'Rossoșanî (UA)',
    neighborCountry: 'UA',
    type: 'ROAD',
    lat: 48.3611,
    lng: 27.0833,
    status: 'NORMAL',
    waitTimeCarsMinutes: 10,
    waitTimeTrucksMinutes: 20,
    waitTimeBusesMinutes: 10,
    isOpen24h: true,
    pedestrianAllowed: false,
  },
  {
    id: 'ptf-ocnita',
    name: 'Ocnița-Sokireanî',
    counterpartName: 'Sokireanî (UA)',
    neighborCountry: 'UA',
    type: 'ROAD',
    lat: 48.4442,
    lng: 27.4381,
    status: 'NORMAL',
    waitTimeCarsMinutes: 10,
    waitTimeTrucksMinutes: 20,
    waitTimeBusesMinutes: 10,
    isOpen24h: true,
    pedestrianAllowed: true,
  },
];

export async function fetchMoldovaBorderCrossings(): Promise<MoldovaBorderCrossing[]> {
  const cacheKey = 'moldova:borders:crossings';

  return fetchWithMoldovaCache<MoldovaBorderCrossing[]>(
    cacheKey,
    async () => {
      return BORDER_CROSSINGS_DATA.map(normalizeBorderCrossing);
    },
    MOLDOVA_CONFIG.cacheTtl.borders,
    BORDER_CROSSINGS_DATA.map(normalizeBorderCrossing),
  );
}
