/**
 * OSIRIS — Moldova Public Telegram Channel & Broadcast Intelligence
 * Catalog and tracking of verified official public Moldovan channels.
 */

import { fetchWithMoldovaCache } from '../cache/moldova-cache';
import type { MoldovaTelegramChannel } from '../types';

export const VERIFIED_MOLDOVA_TELEGRAM_CHANNELS: MoldovaTelegramChannel[] = [
  {
    id: 'tg-politia-rm',
    handle: 'politia_rm',
    title: 'Poliția Republicii Moldova (IGP)',
    category: 'POLICE',
    language: 'ro',
    url: 'https://t.me/politia_rm',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T12:00:00.000Z',
    description: 'Canalul oficial de informare al Inspectoratului General al Poliției: alerte, trafic, ordine publică.',
  },
  {
    id: 'tg-border-police',
    handle: 'borderpolice_md',
    title: 'Poliția de Frontieră a RM',
    category: 'POLICE',
    language: 'ro',
    url: 'https://t.me/borderpolice_md',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T12:00:00.000Z',
    description: 'Situația la punctele de trecere a frontierei de stat (PTF), fluxul de călători și restricții.',
  },
  {
    id: 'tg-igsu-md',
    handle: 'igsu_md',
    title: 'IGSU al MAI (Salvatori și Pompieri)',
    category: 'EMERGENCY',
    language: 'ro',
    url: 'https://t.me/dse_md',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T11:00:00.000Z',
    description: 'Inspectoratul General pentru Situații de Urgență: intervenții, incendii, avertizări meteo critice.',
  },
  {
    id: 'tg-guvernul-rm',
    handle: 'primeminister_md',
    title: 'Guvernul Republicii Moldova',
    category: 'GOVERNMENT',
    language: 'ro',
    url: 'https://t.me/primeminister_md',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T10:00:00.000Z',
    description: 'Deciziile Executivului, ședințe de Guvern, măsuri economice și reforme naționale.',
  },
  {
    id: 'tg-chisinau-primaria',
    handle: 'IonCeban',
    title: 'Primăria Municipiului Chișinău',
    category: 'REGIONAL',
    language: 'ro',
    url: 'https://t.me/IonCeban',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T11:30:00.000Z',
    description: 'Știri municipale Chișinău, reparații de drumuri, transport public și evenimente urbane.',
  },
  {
    id: 'tg-meteo-md',
    handle: 'meteo_moldova',
    title: 'Serviciul Hidrometeorologic de Stat',
    category: 'WEATHER',
    language: 'ro',
    url: 'https://t.me/meteo_moldova',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T08:00:00.000Z',
    description: 'Avertizări meteorologice și hidrologice (Cod Galben, Portocaliu, Roșu), prognoze oficiale.',
  },
  {
    id: 'tg-newsmaker',
    handle: 'newsmakermd',
    title: 'NewsMaker Moldova',
    category: 'NEWS',
    language: 'ru',
    url: 'https://t.me/newsmakermd',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T12:30:00.000Z',
    description: 'Оперативные новости политики, экономики и общества Молдовы на русском и румынском.',
  },
  {
    id: 'tg-zdg',
    handle: 'zdg_md',
    title: 'Ziarul de Gardă (ZdG)',
    category: 'NEWS',
    language: 'ro',
    url: 'https://t.me/zdg_md',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T11:45:00.000Z',
    description: 'Investigații jurnalistice independente, justiție, anticorupție și evenimente de interes public.',
  },
  {
    id: 'tg-tv8',
    handle: 'tv8md',
    title: 'TV8 Moldova',
    category: 'NEWS',
    language: 'ro',
    url: 'https://t.me/tv8md',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T12:15:00.000Z',
    description: 'Știri de ultimă oră, reportaje speciale și emisiuni de analiză socio-politică.',
  },
  {
    id: 'tg-diez',
    handle: 'diez_md',
    title: '#diez Știri pentru Tineri',
    category: 'NEWS',
    language: 'ro',
    url: 'https://t.me/diez_md',
    isOfficial: true,
    status: 'VERIFIED_ACTIVE',
    lastSeen: '2026-09-26T10:30:00.000Z',
    description: 'Educație, cultură, oportunități, tehnologie și evenimente de tineret din Moldova.',
  },
];

export async function fetchMoldovaTelegramChannels(): Promise<MoldovaTelegramChannel[]> {
  const cacheKey = 'moldova:telegram:channels:all';
  return fetchWithMoldovaCache<MoldovaTelegramChannel[]>(
    cacheKey,
    async () => VERIFIED_MOLDOVA_TELEGRAM_CHANNELS,
    60 * 60 * 1000,
    VERIFIED_MOLDOVA_TELEGRAM_CHANNELS,
  );
}
